/*
 * app.h
 *
 *  Created on: 22 jan 2023
 *      Author: klaslofstedt
 */

#ifndef _APP_H_
#define _APP_H_

#include "freertos/event_groups.h"

// #define BLE_RECEIVE_EVENT BIT0
// #define MQTT_RECEIVE_EVENT BIT1
// #define WIFI_SCAN_DONE BIT2

#define APP_EVENT_BLE_GAP_CONNECT BIT0
#define APP_EVENT_BLE_GAP_ADV_COMPLETE BIT1
#define APP_EVENT_BLE_GAP_DISCONNECT BIT2
#define APP_EVENT_BLE_RECEIVE_POP_DONE BIT3
#define APP_EVENT_BLE_RECEIVE_WIFI_CREDS_DONE BIT4
#define APP_EVENT_BLE_RECEIVE_CA_CERT_DONE BIT5
#define APP_EVENT_BLE_NOTIFY_WIFI_SCAN_DONE BIT6
#define APP_EVENT_BLE_NOTIFY_WIFI_CREDS_DONE BIT7
#define APP_EVENT_BLE_NOTIFY_CA_CERT_DONE BIT8
#define APP_EVENT_WIFI_START BIT9
#define APP_EVENT_WIFI_DISCONNECTED BIT10
#define APP_EVENT_WIFI_CONNECTED BIT11
#define APP_EVENT_WIFI_SCAN_DONE BIT12
//#define APP_EVENT_BLE_NOTIFY_DONE BIT13

// in app.c
typedef enum {
    APP_STATE_AWAITING_INIT = 0,
    APP_STATE_AWAITING_BLE_CONNECTION,
    APP_STATE_AWAITING_BLE_RECEIVE_POP,
    APP_STATE_AWAITING_WIFI_SCAN_DONE,
    APP_STATE_AWAITING_BLE_NOTIFY_WIFI_SCAN_DONE,
    APP_STATE_AWAITING_BLE_RECEIVE_WIFI_CREDS,
    APP_STATE_AWAITING_BLE_NOTIFY_WIFI_CREDS_DONE,
    APP_STATE_AWAITING_BLE_RECEIVE_CA_CERT,
    APP_STATE_AWAITING_BLE_NOTIFY_CA_CERT_DONE,
    APP_STATE_AWAITING_WIFI_CONNECTED,
    APP_STATE_NORMAL_OPERATION,
} app_states_t;


//extern EventGroupHandle_t app_events;
extern EventGroupHandle_t app_event_group;

#endif /* _APP_H_ */
