/*
 * app.h
 *
 *  Created on: 22 jan 2023
 *      Author: klaslofstedt
 */

#ifndef _APP_H_
#define _APP_H_

#include "freertos/event_groups.h"

typedef enum {
    APP_EVENT_BLE_GAP_CONNECT = BIT0,
    APP_EVENT_BLE_GAP_ADV_COMPLETE = BIT1,
    APP_EVENT_BLE_GAP_DISCONNECT = BIT2,
    APP_EVENT_BLE_RECEIVE_POP_DONE = BIT3,
    APP_EVENT_BLE_RECEIVE_WIFI_CREDS_DONE = BIT4,
    APP_EVENT_BLE_RECEIVE_WIFI_CREDS_FAIL = BIT5,
    APP_EVENT_BLE_RECEIVE_CA_CERT_DONE = BIT6,
    APP_EVENT_BLE_NOTIFY_WIFI_SCAN_DONE = BIT7,
    APP_EVENT_BLE_NOTIFY_WIFI_CREDS_OK_DONE = BIT8,
    APP_EVENT_BLE_NOTIFY_CA_CERT_DONE = BIT9,
    APP_EVENT_WIFI_START = BIT10,
    APP_EVENT_WIFI_DISCONNECTED = BIT11,
    APP_EVENT_WIFI_CONNECTED = BIT12,
    APP_EVENT_WIFI_SCAN_DONE = BIT13,
    APP_EVENT_UNINITIALISED = BIT14,
    APP_EVENT_BLE_NOTIFY_WIFI_CREDS_ERROR_DONE = BIT15,
} app_events_t;

typedef enum
{
    APP_STATE_UNINITIALISED = BIT0,
    APP_STATE_DO_PRODUCTION = BIT1,
    APP_STATE_DO_PROVISION = BIT2,
    APP_STATE_NORMAL_OPERATION = BIT3,
} app_states_t;

extern EventGroupHandle_t app_event_group;

#endif /* _APP_H_ */
